% REFERENCE: Execute.m

SetEnvironment
SetPath

%% MSRI: Train(1)-Val(2)-Test(3): Windowed Bumblebee data: winlen=[256, 384, 512, 640, 768]    [BALANCED]
Index=[2561, 2562, 2563, 3841, 3842, 3843, 5121, 5122, 5123, 6401, 6402, 6403, 7681, 7682, 7683];
data_noise={'/Targets_balanced/bb_3class_winlen_256_winindex_all/bb_3class_winlen_256_winindex_all_train/Noise', '/Targets_balanced/bb_3class_winlen_256_winindex_all/bb_3class_winlen_256_winindex_all_val/Noise', '/Targets_balanced/bb_3class_winlen_256_winindex_all/bb_3class_winlen_256_winindex_all_test/Noise',...
    '/Targets_balanced/bb_3class_winlen_384_winindex_all/bb_3class_winlen_384_winindex_all_train/Noise', '/Targets_balanced/bb_3class_winlen_384_winindex_all/bb_3class_winlen_384_winindex_all_val/Noise', '/Targets_balanced/bb_3class_winlen_384_winindex_all/bb_3class_winlen_384_winindex_all_test/Noise',...
    '/Targets_balanced/bb_3class_winlen_512_winindex_all/bb_3class_winlen_512_winindex_all_train/Noise', '/Targets_balanced/bb_3class_winlen_512_winindex_all/bb_3class_winlen_512_winindex_all_val/Noise', '/Targets_balanced/bb_3class_winlen_512_winindex_all/bb_3class_winlen_512_winindex_all_test/Noise',...
    '/Targets_balanced/bb_3class_winlen_640_winindex_all/bb_3class_winlen_640_winindex_all_train/Noise', '/Targets_balanced/bb_3class_winlen_640_winindex_all/bb_3class_winlen_640_winindex_all_val/Noise', '/Targets_balanced/bb_3class_winlen_640_winindex_all/bb_3class_winlen_640_winindex_all_test/Noise',...
    '/Targets_balanced/bb_3class_winlen_768_winindex_all/bb_3class_winlen_768_winindex_all_train/Noise', '/Targets_balanced/bb_3class_winlen_768_winindex_all/bb_3class_winlen_768_winindex_all_val/Noise', '/Targets_balanced/bb_3class_winlen_768_winindex_all/bb_3class_winlen_768_winindex_all_test/Noise'};

data_dog={'/Targets_balanced/bb_3class_winlen_256_winindex_all/bb_3class_winlen_256_winindex_all_train/Nonhuman', '/Targets_balanced/bb_3class_winlen_256_winindex_all/bb_3class_winlen_256_winindex_all_val/Nonhuman', '/Targets_balanced/bb_3class_winlen_256_winindex_all/bb_3class_winlen_256_winindex_all_test/Nonhuman',...
    '/Targets_balanced/bb_3class_winlen_384_winindex_all/bb_3class_winlen_384_winindex_all_train/Nonhuman', '/Targets_balanced/bb_3class_winlen_384_winindex_all/bb_3class_winlen_384_winindex_all_val/Nonhuman', '/Targets_balanced/bb_3class_winlen_384_winindex_all/bb_3class_winlen_384_winindex_all_test/Nonhuman',...
    '/Targets_balanced/bb_3class_winlen_512_winindex_all/bb_3class_winlen_512_winindex_all_train/Nonhuman', '/Targets_balanced/bb_3class_winlen_512_winindex_all/bb_3class_winlen_512_winindex_all_val/Nonhuman', '/Targets_balanced/bb_3class_winlen_512_winindex_all/bb_3class_winlen_512_winindex_all_test/Nonhuman',...
    '/Targets_balanced/bb_3class_winlen_640_winindex_all/bb_3class_winlen_640_winindex_all_train/Nonhuman', '/Targets_balanced/bb_3class_winlen_640_winindex_all/bb_3class_winlen_640_winindex_all_val/Nonhuman', '/Targets_balanced/bb_3class_winlen_640_winindex_all/bb_3class_winlen_640_winindex_all_test/Nonhuman',...
    '/Targets_balanced/bb_3class_winlen_768_winindex_all/bb_3class_winlen_768_winindex_all_train/Nonhuman', '/Targets_balanced/bb_3class_winlen_768_winindex_all/bb_3class_winlen_768_winindex_all_val/Nonhuman', '/Targets_balanced/bb_3class_winlen_768_winindex_all/bb_3class_winlen_768_winindex_all_test/Nonhuman'};

data_human={'/Targets_balanced/bb_3class_winlen_256_winindex_all/bb_3class_winlen_256_winindex_all_train/Human', '/Targets_balanced/bb_3class_winlen_256_winindex_all/bb_3class_winlen_256_winindex_all_val/Human', '/Targets_balanced/bb_3class_winlen_256_winindex_all/bb_3class_winlen_256_winindex_all_test/Human',...
    '/Targets_balanced/bb_3class_winlen_384_winindex_all/bb_3class_winlen_384_winindex_all_train/Human', '/Targets_balanced/bb_3class_winlen_384_winindex_all/bb_3class_winlen_384_winindex_all_val/Human', '/Targets_balanced/bb_3class_winlen_384_winindex_all/bb_3class_winlen_384_winindex_all_test/Human',...
    '/Targets_balanced/bb_3class_winlen_512_winindex_all/bb_3class_winlen_512_winindex_all_train/Human', '/Targets_balanced/bb_3class_winlen_512_winindex_all/bb_3class_winlen_512_winindex_all_val/Human', '/Targets_balanced/bb_3class_winlen_512_winindex_all/bb_3class_winlen_512_winindex_all_test/Human',...
    '/Targets_balanced/bb_3class_winlen_640_winindex_all/bb_3class_winlen_640_winindex_all_train/Human', '/Targets_balanced/bb_3class_winlen_640_winindex_all/bb_3class_winlen_640_winindex_all_val/Human', '/Targets_balanced/bb_3class_winlen_640_winindex_all/bb_3class_winlen_640_winindex_all_test/Human',...
    '/Targets_balanced/bb_3class_winlen_768_winindex_all/bb_3class_winlen_768_winindex_all_train/Human', '/Targets_balanced/bb_3class_winlen_768_winindex_all/bb_3class_winlen_768_winindex_all_val/Human', '/Targets_balanced/bb_3class_winlen_768_winindex_all/bb_3class_winlen_768_winindex_all_test/Human'};
%% Execute_3class.m
featureClass = 0;

for i=1:length(Index)
    OutIndex = Index(i);
    fprintf('Processing OutIndex=%d...\n', OutIndex);
    [feature_min, scalingFactors] = Build_arff_3class(OutIndex,0,featureClass, 0, 0, data_human{i}, data_dog{i}, data_noise{i});
end

fprintf('All done!\n');