SetEnvironment;
SetPath;

cd(g_str_pathbase_model);
delete('*.model');

[crossval_InfoGain, crossval_mRMR_D, crossenvironment_InfoGain, crossenvironment_mRMR_D,...
crossval_mRMRV_D_norm_25, crossenvironment_mRMRV_D_norm_25, crossval_mRMRV_D_norm_50, crossenvironment_mRMRV_D_norm_50,...
crossval_mRMRV_D_norm_75, crossenvironment_mRMRV_D_norm_75, crossval_mRMRV_D_norm_full, crossenvironment_mRMRV_D_norm_full,...
crossval_mRMRV_D_norm_10x, crossenvironment_mRMRV_D_norm_10x, crossval_mRMRV_D_norm_50x, crossenvironment_mRMRV_D_norm_50x,...
crossval_mRMRV_D_norm_100x, crossenvironment_mRMRV_D_norm_100x]=RunResultsScript_SenSys('jin_emote', 40);